### ISSUE TITLE
Acunetix needs a dummy value to work

### ISSUE THREAD

**Issue by DanBrown47** [Bandit-HaxUnit/haxunit#1]
-acu is expecting a value, any would work to initialize in python3.9 

Could be fixed on configuring the argument parser.

Assign to me to fix +1

**Comment by c4ng4c3ir0** [comment]
How did you make acunetix work? here it still has problems, even informing any value after the -acu

**Comment by Bandit-HaxUnit** [comment]
Hi, the argument to -acu needs to be the 'ui_session' cookie value after logging in.

I will look into automating this part soon!

**Comment by Bandit-HaxUnit** [comment]
Hi @DanBrown47 - I've added a tutorial here:
https://github.com/Bandit-HaxUnit/haxunit#using-acunetix

**Comment by DanBrown47** [comment]
Thanks that's helpful
