### ISSUE TITLE
Acunetix Not Work

### ISSUE THREAD

**Issue by c4ng4c3ir0** [Bandit-HaxUnit/haxunit#3]
Hello.
I'm trying to use the scanner with acunetix, but I'm getting this error. How should I do? Would you have a specific usage tutorial for this command?
Note: I am correctly informing the token in -acu.

![image](https://user-images.githubusercontent.com/54048948/159256238-e532741c-85be-4d18-bd03-07a648e167a6.png)

**Comment by Bandit-HaxUnit** [comment]
Hi @c4ng4c3ir0 - I've fixed this issue and I've added a tutorial on how to use `-acu`:
https://github.com/Bandit-HaxUnit/haxunit#using-acunetix
